//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringNuget.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abrechnung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abrechnung()
        {
            this.Abrechnungsposition = new HashSet<Abrechnungsposition>();
        }
    
        public int Id { get; set; }
        public int PodAbrechnungId { get; set; }
        public decimal Bruttopreis { get; set; }
        public decimal UsedGuthaben { get; set; }
        public decimal Nettopreis { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abrechnungsposition> Abrechnungsposition { get; set; }
        public virtual Point_Of_Delivery Point_Of_Delivery { get; set; }
    }
}
