//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringNuget.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abrechnungsposition
    {
        public int Id { get; set; }
        public string Produktbeschreibung { get; set; }
        public decimal Stueckpreis { get; set; }
        public int Menge { get; set; }
        public int PodId { get; set; }
        public Nullable<bool> isFakturiert { get; set; }
        public System.DateTime Buchungsdatum { get; set; }
        public Nullable<int> AbrechnungId { get; set; }
    
        public virtual Abrechnung Abrechnung { get; set; }
        public virtual Point_Of_Delivery Point_Of_Delivery { get; set; }
    }
}
