//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringNuget.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jahresvergleich
    {
        public string Kategorie { get; set; }
        public string YOY { get; set; }
        public Nullable<decimal> Q3_2020 { get; set; }
        public Nullable<decimal> Q2_2020 { get; set; }
        public Nullable<decimal> Q1_2020 { get; set; }
        public Nullable<decimal> Q4_2019 { get; set; }
    }
}
