//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringNuget.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class JahresVergleichOne
    {
        public string Kategorie { get; set; }
        public string YOY { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<decimal> NUM { get; set; }
    }
}
