//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringNuget.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontaktperson
    {
        public int Id { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public int Prioritaet { get; set; }
        public int PodId { get; set; }
    
        public virtual Point_Of_Delivery Point_Of_Delivery { get; set; }
    }
}
