//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringNuget.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kunde()
        {
            this.Point_Of_Delivery = new HashSet<Point_Of_Delivery>();
        }
    
        public int Id { get; set; }
        public string Kontonr { get; set; }
        public string Bezeichnung { get; set; }
        public decimal Guthaben { get; set; }
        public decimal Betragslimit { get; set; }
        public string Telefonnummer { get; set; }
        public string EMail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point_Of_Delivery> Point_Of_Delivery { get; set; }
    }
}
