//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringNuget.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logmessage
    {
        public int Id { get; set; }
        public System.DateTime Zeitstempel { get; set; }
        public int Severity { get; set; }
        public string LogMessage1 { get; set; }
        public int DeviceId { get; set; }
        public bool isChecked { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Severity Severity1 { get; set; }
    }
}
