//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringNuget.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UsagePerLocation
    {
        public string LocationName { get; set; }
        public string CategoryName { get; set; }
        public string hostname { get; set; }
        public string ip_adresse { get; set; }
        public int MaxPorts { get; set; }
        public Nullable<int> UsedPorts { get; set; }
        public Nullable<int> Auslastung { get; set; }
    }
}
